<a href="https://colab.research.google.com/github/pothineni1/AIML/blob/main/Python_interview/Q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
req_skills = {'Pyhton','aws','snowflake','docker','sql'}
type(req_skills)

set

In [2]:
table_data = { "Candidate_id": ['C001','C002','C003','C004','C005'],
              "skills": ["Pyhton,aws,docker,sql",
                         "Pyhton,aws,snowflake,docker,sql",
                         "java,sql",
                         "Pyhton,aws,docker,snowflake",
                         "Pyhton,docker,sql"]
              }
table_data

{'Candidate_id': ['C001', 'C002', 'C003', 'C004', 'C005'],
 'skills': ['Pyhton,aws,docker,sql',
  'Pyhton,aws,snowflake,docker,sql',
  'java,sql',
  'Pyhton,aws,docker,snowflake',
  'Pyhton,docker,sql']}

In [3]:
import pandas as pd

In [4]:
df_table = pd.DataFrame(table_data)
df_table

  Candidate_id                           skills
0         C001            Pyhton,aws,docker,sql
1         C002  Pyhton,aws,snowflake,docker,sql
2         C003                         java,sql
3         C004      Pyhton,aws,docker,snowflake
4         C005                Pyhton,docker,sql

In [5]:
def percentage_match(skills):
  cand_skilss = {s.strip() for s in skills.split(",")}
  matched_skills = cand_skilss.intersection(req_skills)

  return  (len(matched_skills)/len(req_skills))*100

In [6]:
df_table["percentage_match"] = df_table['skills'].apply(percentage_match)
df_table

  Candidate_id                           skills  percentage_match
0         C001            Pyhton,aws,docker,sql              80.0
1         C002  Pyhton,aws,snowflake,docker,sql             100.0
2         C003                         java,sql              20.0
3         C004      Pyhton,aws,docker,snowflake              80.0
4         C005                Pyhton,docker,sql              60.0

In [7]:
result = df_table[df_table["percentage_match"] >= 80]
display(result)

  Candidate_id                           skills  percentage_match
0         C001            Pyhton,aws,docker,sql              80.0
1         C002  Pyhton,aws,snowflake,docker,sql             100.0
3         C004      Pyhton,aws,docker,snowflake              80.0

In [11]:
for i in df_table['skills']:
  print(i.strip())

Pyhton,aws,docker,sql
Pyhton,aws,snowflake,docker,sql
java,sql
Pyhton,aws,docker,snowflake
Pyhton,docker,sql