<a href="https://colab.research.google.com/github/pothineni1/AIML/blob/main/Pandas/Pandas_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
print(pd.__version__)

2.2.3

In [4]:
print(dir(pd))

['ArrowDtype', 'BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_built_with_meson', '_config', '_is_numpy_dev', '_libs', '_pandas_datetime_CAPI', '_pandas_parser_CAPI', '_testing', '_typing', '_version_meson', 'annotations', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'concat', 'core', 'crosstab', 'cut', 'date_range', 'describe_option', 'errors', 'eval', 'factorize', 'from_dummies', 'get_dummies', 'get_option', 'infer_freq', 'interval_range', 'io', 'isna', 'isnull', 'json_normalize', 'lreshape', 'melt', 'merge', 'merge_asof', 'merge_ordered', 'notna', 'notnull', 'offsets', 'option_context', 'options', 'pandas', 'period_range', 'pivot', 'pivot_table', 'plotting', 'qcut', 'read_clipboard', 'read_csv', 'read_excel', 'read_feather', 'read_fwf', 'read_gbq', 'read_hdf', 'read_html', 'read_json', 'read_orc', 'read_parquet', 'read_pickle', 'read_sas', 'read_spss', 'read_sql', 'read_sql_query', 'read_sql_table', 'read_stata', 'read_table', 'read_xml', 'reset_option', 'set_eng_float_format', 'set_option', 'show_versions', 'test', 'testing', 'timedelta_range', 'to_datetime', 'to_numeric', 'to_pickle', 'to_timedelta', 'tseries', 'unique', 'util', 'value_counts', 'wide_to_long']

## Series Data - single dimention only one column

In [5]:
age = [21,22,23,24,45]
df1 = pd.Series(age, name = 'Age')
df1

0    21
1    22
2    23
3    24
4    45
Name: Age, dtype: int64

In [6]:
df1.max() , df1.min(), df1.mean(), df1.median, df1.mode, df1.std()

(45,
 21,
 np.float64(27.0),
 <bound method Series.median of 0    21
 1    22
 2    23
 3    24
 4    45
 Name: Age, dtype: int64>,
 <bound method Series.mode of 0    21
 1    22
 2    23
 3    24
 4    45
 Name: Age, dtype: int64>,
 10.124228365658293)

In [7]:
for i in df1:
  print(i)

21
22
23
24
45

Data Frame -- Multi dimention rows and columns

In [8]:
df2 = pd.DataFrame([[21,2,25000],[22,3,26000],[30,10,50000],[35,15,100000]], columns= ['Age','Exp','Sal'])
##display(df2)
df2

   Age  Exp     Sal
0   21    2   25000
1   22    3   26000
2   30   10   50000
3   35   15  100000

In [9]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     4 non-null      int64
 1   Exp     4 non-null      int64
 2   Sal     4 non-null      int64
dtypes: int64(3)
memory usage: 228.0 bytes

In [10]:
df3 = pd.read_csv('/content/sample_data/california_housing_train.csv')
df3

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [11]:
df3.columns.tolist()

['longitude',
 'latitude',
 'housing_median_age',
 'total_rooms',
 'total_bedrooms',
 'population',
 'households',
 'median_income',
 'median_house_value']

In [12]:
df3.max()

longitude               -114.3100
latitude                  41.9500
housing_median_age        52.0000
total_rooms            37937.0000
total_bedrooms          6445.0000
population             35682.0000
households              6082.0000
median_income             15.0001
median_house_value    500001.0000
dtype: float64

In [13]:
df3.index

RangeIndex(start=0, stop=17000, step=1)

In [14]:
# Super market Data
items = ['appels', 'oranges', 'water_melons', 'kiwi']
price_2025 = (105, 82, 35, 67)
price_2024 = (115,78,48,87)

In [15]:
df_super = pd.DataFrame({'Product':items, 'new_price':price_2025, 'old_proce':price_2024})
df_super

        Product  new_price  old_proce
0        appels        105        115
1       oranges         82         78
2  water_melons         35         48
3          kiwi         67         87

In [16]:
df_super.shape

(4, 3)

In [17]:
df_super.columns

Index(['Product', 'new_price', 'old_proce'], dtype='object')

In [18]:
df_super.index

RangeIndex(start=0, stop=4, step=1)

In [19]:
df_super['Difference']=((df_super['old_proce']-df_super['new_price'])/df_super['old_proce'])*100
df_super

        Product  new_price  old_proce  Difference
0        appels        105        115    8.695652
1       oranges         82         78   -5.128205
2  water_melons         35         48   27.083333
3          kiwi         67         87   22.988506

In [20]:
print(df_super.to_string(index=False))

     Product  new_price  old_proce  Difference
      appels        105        115    8.695652
     oranges         82         78   -5.128205
water_melons         35         48   27.083333
        kiwi         67         87   22.988506

In [21]:
display(df_super.style.hide(axis='index'))

In [22]:
df_super[0:4:2]

        Product  new_price  old_proce  Difference
0        appels        105        115    8.695652
2  water_melons         35         48   27.083333

In [23]:
df_super['Product']

0          appels
1         oranges
2    water_melons
3            kiwi
Name: Product, dtype: object

In [24]:
df_super[['Product','new_price']]

        Product  new_price
0        appels        105
1       oranges         82
2  water_melons         35
3          kiwi         67

In [25]:
selected = df_super.iloc[0:3, 0:2]
display(selected)

        Product  new_price
0        appels        105
1       oranges         82
2  water_melons         35

## Export the data

In [26]:
import os
df_super.to_excel('super.xlsx', sheet_name='first', index=False)
os.getcwd()

'/content'

In [27]:
df_super.style.hide(axis='index')

In [28]:
df_cars = pd.read_csv('https://raw.githubusercontent.com/pothineni1/AIML/refs/heads/main/cars.csv',delimiter=',')
df_cars

,id,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Updated_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
4,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6015,6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,7.88 Lakh,4.75
6016,6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.0,NaN,4.00
6017,6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.0,NaN,2.90
6018,6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.0,NaN,2.65
6019,6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,NaN,2.50

In [29]:
df_cars.columns

Index(['id', 'Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'Updated_Price', 'Price'],
      dtype='object')

In [30]:
df_fual_cons= pd.read_excel('https://github.com/pothineni1/AIML/raw/main/Fuel_consumption.xlsx',sheet_name='Sheet1')
df_fual_cons

      Snr  Year   MAKE           MODEL
0    1101  2000  ACURA           1.6EL
1    1102  2000  ACURA           1.6EL
2    1103  2000  ACURA           3.2TL
3    1104  2000  ACURA           3.5RL
4    1105  2000  ACURA         INTEGRA
..    ...   ...    ...             ...
634  1735  2000  VOLVO   V70 AWD TURBO
635  1736  2000  VOLVO   V70 GLT TURBO
636  1737  2000  VOLVO    V70 T5 TURBO
637  1738  2000  VOLVO    V70 T5 TURBO
638  1739  2000  VOLVO  V70R AWD TURBO

[639 rows x 4 columns]

In [31]:
df_cars.style.hide(axis='index')

In [32]:
df_cars.head()

,id,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Updated_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
4,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00

In [33]:
df_cars.tail()

,id,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Updated_Price,Price
6015,6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,7.88 Lakh,4.75
6016,6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.0,NaN,4.00
6017,6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.0,NaN,2.90
6018,6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.0,NaN,2.65
6019,6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,NaN,2.50

In [34]:
df_cars.head(1)

,id,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Updated_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75

In [35]:
df_cars.tail(1)

,id,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Updated_Price,Price
6019,6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,NaN,2.5

In [36]:
df_cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6020 entries, 0 to 6019
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 6020 non-null   int64
 1   Name               6020 non-null   object
 2   Location           6020 non-null   object
 3   Year               6020 non-null   int64
 4   Kilometers_Driven  6020 non-null   int64
 5   Fuel_Type          6020 non-null   object
 6   Transmission       6020 non-null   object
 7   Owner_Type         6020 non-null   object
 8   Mileage            6018 non-null   object
 9   Engine             5984 non-null   object
 10  Power              5984 non-null   object
 11  Seats              5978 non-null   float64
 12  Updated_Price      825 non-null    object
 13  Price              6020 non-null   float64
dtypes: float64(2), int64(3), object(9)
memory usage: 658.6+ KB

In [37]:
df_cars.describe()

                id         Year  Kilometers_Driven        Seats        Price
count  6020.000000  6020.000000       6.020000e+03  5978.000000  6020.000000
mean   3008.500498  2013.357807       5.873626e+04     5.278689     9.478641
std    1737.967779     3.269612       9.126141e+04     0.808780    11.187172
min       0.000000  1998.000000       1.710000e+02     0.000000     0.440000
25%    1503.750000  2011.000000       3.400000e+04     5.000000     3.500000
50%    3008.500000  2014.000000       5.300000e+04     5.000000     5.640000
75%    4513.250000  2016.000000       7.300000e+04     5.000000     9.950000
max    6018.000000  2019.000000       6.500000e+06    10.000000   160.000000

In [38]:
df_cars[0:11:2]

,id,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Updated_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
4,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
6,5,Hyundai EON LPG Era Plus Option,Hyderabad,2012,75000,LPG,Manual,First,21.1 km/kg,814 CC,55.2 bhp,5.0,NaN,2.35
8,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,Diesel,Automatic,First,11.36 kmpl,2755 CC,171.5 bhp,8.0,21 Lakh,17.50
10,9,Tata Indica Vista Quadrajet LS,Chennai,2012,65932,Diesel,Manual,Second,22.3 kmpl,1248 CC,74 bhp,5.0,NaN,1.95

In [39]:
start = int(input('enter start row: ')) ## Used to insert the data manually
stop = int(input('Enter stop row: '))
step = int(input('Enter step values: '))
df_cars[start:stop:step]

enter start row: 10
Enter stop row: 20
Enter step values: 1

,id,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Updated_Price,Price
10,9,Tata Indica Vista Quadrajet LS,Chennai,2012,65932,Diesel,Manual,Second,22.3 kmpl,1248 CC,74 bhp,5.0,NaN,1.95
11,10,Maruti Ciaz Zeta,Kochi,2018,25692,Petrol,Manual,First,21.56 kmpl,1462 CC,103.25 bhp,5.0,10.65 Lakh,9.95
12,11,Honda City 1.5 V AT Sunroof,Kolkata,2012,60000,Petrol,Automatic,First,16.8 kmpl,1497 CC,116.3 bhp,5.0,NaN,4.49
13,12,Maruti Swift VDI BSIV,Jaipur,2015,64424,Diesel,Manual,First,25.2 kmpl,1248 CC,74 bhp,5.0,NaN,5.60
14,13,Land Rover Range Rover 2.2L Pure,Delhi,2014,72000,Diesel,Automatic,First,12.7 kmpl,2179 CC,187.7 bhp,5.0,NaN,27.00
15,14,Land Rover Freelander 2 TD4 SE,Pune,2012,85000,Diesel,Automatic,Second,0.0 kmpl,2179 CC,115 bhp,5.0,NaN,17.50
16,15,Mitsubishi Pajero Sport 4X4,Delhi,2014,110000,Diesel,Manual,First,13.5 kmpl,2477 CC,175.56 bhp,7.0,32.01 Lakh,15.00
17,16,Honda Amaze S i-Dtech,Kochi,2016,58950,Diesel,Manual,First,25.8 kmpl,1498 CC,98.6 bhp,5.0,NaN,5.40
18,17,Maruti Swift DDiS VDI,Jaipur,2017,25000,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,NaN,5.99
19,18,Renault Duster 85PS Diesel RxL Plus,Kochi,2014,77469,Diesel,Manual,First,20.45 kmpl,1461 CC,83.8 bhp,5.0,NaN,6.34

In [40]:
## Column Indexing
df_interested= df_cars[['Location','Year','Fuel_Type']][100:120].reset_index()
df_interested

    index    Location  Year Fuel_Type
0     100       Delhi  2010    Petrol
1     101        Pune  2011    Diesel
2     102      Mumbai  2014    Petrol
3     103        Pune  2017    Petrol
4     104     Kolkata  2010    Diesel
5     105        Pune  2009    Petrol
6     106  Coimbatore  2010    Petrol
7     107   Ahmedabad  2014    Petrol
8     108   Hyderabad  2011    Diesel
9     109       Delhi  2012    Diesel
10    110     Kolkata  2014    Diesel
11    111      Mumbai  2017    Diesel
12    112  Coimbatore  2017    Petrol
13    113   Bangalore  2014    Petrol
14    114      Mumbai  2015    Diesel
15    115       Delhi  2010    Petrol
16    116   Ahmedabad  2014    Diesel
17    117   Bangalore  2014    Diesel
18    118  Coimbatore  2016    Petrol
19    119      Mumbai  2009    Petrol

In [41]:
df_cars.loc[100:120 , ['Location','Year','Fuel_Type']].reset_index()

    index    Location  Year Fuel_Type
0     100       Delhi  2010    Petrol
1     101        Pune  2011    Diesel
2     102      Mumbai  2014    Petrol
3     103        Pune  2017    Petrol
4     104     Kolkata  2010    Diesel
5     105        Pune  2009    Petrol
6     106  Coimbatore  2010    Petrol
7     107   Ahmedabad  2014    Petrol
8     108   Hyderabad  2011    Diesel
9     109       Delhi  2012    Diesel
10    110     Kolkata  2014    Diesel
11    111      Mumbai  2017    Diesel
12    112  Coimbatore  2017    Petrol
13    113   Bangalore  2014    Petrol
14    114      Mumbai  2015    Diesel
15    115       Delhi  2010    Petrol
16    116   Ahmedabad  2014    Diesel
17    117   Bangalore  2014    Diesel
18    118  Coimbatore  2016    Petrol
19    119      Mumbai  2009    Petrol
20    120      Mumbai  2016    Diesel

In [42]:
df_cars

,id,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Updated_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
4,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6015,6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,7.88 Lakh,4.75
6016,6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.0,NaN,4.00
6017,6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.0,NaN,2.90
6018,6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.0,NaN,2.65
6019,6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,NaN,2.50

In [43]:
for i in df_cars['Location']:
  print(i)

Mumbai
Pune
Chennai
Chennai
Chennai
Coimbatore
Hyderabad
Jaipur
Mumbai
Pune
Chennai
Kochi
Kolkata
Jaipur
Delhi
Pune
Delhi
Kochi
Jaipur
Kochi
Bangalore
Kochi
Bangalore
Mumbai
Kolkata
Kolkata
Mumbai
Hyderabad
Hyderabad
Kochi
Mumbai
Bangalore
Delhi
Bangalore
Kolkata
Coimbatore
Jaipur
Kochi
Delhi
Pune
Chennai
Delhi
Kochi
Coimbatore
Kochi
Bangalore
Mumbai
Ahmedabad
Bangalore
Jaipur
Jaipur
Kochi
Delhi
Kolkata
Delhi
Chennai
Kolkata
Kochi
Kolkata
Hyderabad
Hyderabad
Mumbai
Bangalore
Delhi
Pune
Chennai
Jaipur
Mumbai
Coimbatore
Pune
Mumbai
Mumbai
Mumbai
Kochi
Kochi
Coimbatore
Delhi
Jaipur
Chennai
Hyderabad
Hyderabad
Jaipur
Pune
Kochi
Hyderabad
Jaipur
Delhi
Delhi
Pune
Bangalore
Hyderabad
Mumbai
Delhi
Coimbatore
Delhi
Delhi
Kolkata
Kolkata
Ahmedabad
Bangalore
Delhi
Pune
Mumbai
Pune
Kolkata
Pune
Coimbatore
Ahmedabad
Hyderabad
Delhi
Kolkata
Mumbai
Coimbatore
Bangalore
Mumbai
Delhi
Ahmedabad
Bangalore
Coimbatore
Mumbai
Mumbai
Mumbai
Pune
Kolkata
Pune
Coimbatore
Kolkata
Kolkata
Pune
Bangalore
Pune
Kochi
Jaipur
Coimbatore
Hyderabad
Kolkata
Kochi
Chennai
Coimbatore
Mumbai
Delhi
Kochi
Kolkata
Kochi
Kochi
Coimbatore
Pune
Chennai
Kochi
Mumbai
Mumbai
Coimbatore
Chennai
Kolkata
Coimbatore
Pune
Kochi
Jaipur
Kolkata
Kolkata
Delhi
Kochi
Ahmedabad
Ahmedabad
Mumbai
Kochi
Mumbai
Chennai
Jaipur
Mumbai
Coimbatore
Bangalore
Delhi
Bangalore
Kolkata
Mumbai
Mumbai
Jaipur
Bangalore
Mumbai
Jaipur
Kochi
Chennai
Hyderabad
Jaipur
Hyderabad
Mumbai
Bangalore
Kochi
Delhi
Kochi
Kochi
Coimbatore
Chennai
Mumbai
Ahmedabad
Kolkata
Jaipur
Kolkata
Hyderabad
Delhi
Chennai
Mumbai
Kochi
Jaipur
Pune
Delhi
Mumbai
Delhi
Kolkata
Kochi
Kolkata
Jaipur
Mumbai
Delhi
Mumbai
Kolkata
Delhi
Pune
Mumbai
Hyderabad
Coimbatore
Kolkata
Chennai
Hyderabad
Coimbatore
Kolkata
Coimbatore
Delhi
Kochi
Bangalore
Jaipur
Kochi
Mumbai
Hyderabad
Kolkata
Kochi
Mumbai
Kolkata
Kochi
Kochi
Mumbai
Kochi
Coimbatore
Chennai
Mumbai
Mumbai
Kochi
Ahmedabad
Mumbai
Chennai
Kolkata
Kochi
Jaipur
Coimbatore
Jaipur
Kochi
Pune
Jaipur
Coimbatore
Mumbai
Pune
Hyderabad
Hyderabad
Mumbai
Coimbatore
Bangalore
Hyderabad
Bangalore
Pune
Delhi
Delhi
Coimbatore
Bangalore
Pune
Mumbai
Hyderabad
Pune
Pune
Mumbai
Jaipur
Kochi
Jaipur
Kochi
Mumbai
Kochi
Jaipur
Kolkata
Coimbatore
Hyderabad
Ahmedabad
Pune
Pune
Delhi
Delhi
Coimbatore
Hyderabad
Kochi
Pune
Chennai
Kochi
Hyderabad
Mumbai
Hyderabad
Mumbai
Coimbatore
Kochi
Delhi
Chennai
Kolkata
Hyderabad
Hyderabad
Delhi
Hyderabad
Hyderabad
Kochi
Hyderabad
Pune
Delhi
Hyderabad
Pune
Mumbai
Mumbai
Kolkata
Hyderabad
Kolkata
Kochi
Mumbai
Coimbatore
Pune
Pune
Bangalore
Kochi
Hyderabad
Pune
Kolkata
Ahmedabad
Chennai
Chennai
Pune
Pune
Kolkata
Kolkata
Coimbatore
Chennai
Delhi
Hyderabad
Kolkata
Coimbatore
Kochi
Bangalore
Ahmedabad
Jaipur
Pune
Mumbai
Kolkata
Hyderabad
Jaipur
Kochi
Chennai
Delhi
Mumbai
Chennai
Mumbai
Pune
Kolkata
Pune
Kolkata
Kolkata
Bangalore
Bangalore
Mumbai
Coimbatore
Hyderabad
Mumbai
Chennai
Chennai
Chennai
Mumbai
Chennai
Hyderabad
Kochi
Kochi
Jaipur
Kochi
Bangalore
Mumbai
Hyderabad
Chennai
Pune
Mumbai
Delhi
Bangalore
Coimbatore
Chennai
Kolkata
Coimbatore
Chennai
Pune
Chennai
Hyderabad
Pune
Hyderabad
Jaipur
Pune
Coimbatore
Pune
Hyderabad
Bangalore
Hyderabad
Kochi
Coimbatore
Jaipur
Kochi
Mumbai
Pune
Chennai
Pune
Jaipur
Coimbatore
Kolkata
Kochi
Mumbai
Kolkata
Mumbai
Hyderabad
Coimbatore
Mumbai
Mumbai
Pune
Bangalore
Delhi
Coimbatore
Coimbatore
Kochi
Coimbatore
Coimbatore
Kochi
Bangalore
Ahmedabad
Kolkata
Kochi
Kolkata
Coimbatore
Coimbatore
Hyderabad
Coimbatore
Mumbai
Pune
Hyderabad
Kochi
Coimbatore
Bangalore
Chennai
Chennai
Hyderabad
Hyderabad
Delhi
Coimbatore
Bangalore
Coimbatore
Pune
Hyderabad
Pune
Delhi
Hyderabad
Kolkata
Ahmedabad
Kolkata
Bangalore
Hyderabad
Coimbatore
Delhi
Chennai
Kochi
Chennai
Kolkata
Delhi
Hyderabad
Mumbai
Mumbai
Delhi
Chennai
Hyderabad
Coimbatore
Kolkata
Jaipur
Pune
Kolkata
Kolkata
Pune
Hyderabad
Bangalore
Jaipur
Kochi
Jaipur
Chennai
Pune
Chennai
Kochi
Mumbai
Ahmedabad
Mumbai
Kochi
Delhi
Mumbai
Hyderabad
Pune
Mumbai
Mumbai
Bangalore
Pune
Hyderabad
Kochi
Delhi
Pune
Coimbatore
Hyderabad
Coimbatore
Ahmedabad
Chennai
Jaipur
Coimbatore
Pune
Ahmedabad
Coimbatore
Kochi
Kochi
Coimbatore
Kochi
Hyderabad
Mumbai
Coimbatore
Jaipur
Mumbai
Coimbatore
Jaipur
Kolkata
Hyderabad
Hyderabad
Coimbatore
Delhi
Mumbai
Delhi
Bangalore
Kochi
Mumbai
Mumbai
Ahmedabad
Delhi
Coimbatore
Kochi
Delhi
Pune
Pune
Ahmedabad
Pune
Chennai
Delhi
Hyderabad
Hyderabad
Jaipur
Chennai
Ahmedabad
Bangalore
Jaipur
Kochi
Kochi
Coimbatore
Jaipur
Pune
Kolkata
Chennai
Coimbatore
Jaipur
Chennai
Chennai
Hyderabad
Chennai
Coimbatore
Coimbatore
Coimbatore
Kolkata
Kochi
Chennai
Mumbai
Mumbai
Kochi
Kolkata
Bangalore
Bangalore
Ahmedabad
Hyderabad
Delhi
Mumbai
Hyderabad
Kochi
Kochi
Mumbai
Delhi
Coimbatore
Mumbai
Bangalore
Pune
Mumbai
Mumbai
Ahmedabad
Hyderabad
Jaipur
Coimbatore
Bangalore
Coimbatore
Pune
Coimbatore
Kolkata
Mumbai
Hyderabad
Hyderabad
Delhi
Pune
Mumbai
Coimbatore
Mumbai
Kochi
Hyderabad
Chennai
Pune
Kochi
Delhi
Hyderabad
Chennai
Chennai
Chennai
Mumbai
Hyderabad
Delhi
Jaipur
Kochi
Kolkata
Jaipur
Mumbai
Coimbatore
Hyderabad
Kolkata
Coimbatore
Bangalore
Delhi
Kolkata
Jaipur
Jaipur
Delhi
Jaipur
Coimbatore
Chennai
Jaipur
Bangalore
Mumbai
Chennai
Mumbai
Chennai
Coimbatore
Mumbai
Jaipur
Mumbai
Delhi
Jaipur
Pune
Pune
Pune
Coimbatore
Pune
Pune
Kochi
Hyderabad
Hyderabad
Jaipur
Bangalore
Mumbai
Hyderabad
Jaipur
Kochi
Pune
Pune
Chennai
Bangalore
Hyderabad
Hyderabad
Chennai
Hyderabad
Pune
Bangalore
Hyderabad
Kochi
Mumbai
Coimbatore
Hyderabad
Bangalore
Kolkata
Bangalore
Jaipur
Pune
Coimbatore
Chennai
Coimbatore
Coimbatore
Kochi
Kochi
Chennai
Pune
Pune
Delhi
Jaipur
Hyderabad
Hyderabad
Kochi
Hyderabad
Kolkata
Kochi
Bangalore
Pune
Coimbatore
Bangalore
Kochi
Kolkata
Ahmedabad
Mumbai
Jaipur
Kochi
Chennai
Pune
Pune
Kochi
Kolkata
Delhi
Chennai
Kolkata
Coimbatore
Kochi
Bangalore
Hyderabad
Bangalore
Coimbatore
Ahmedabad
Delhi
Delhi
Kochi
Chennai
Hyderabad
Chennai
Hyderabad
Mumbai
Bangalore
Coimbatore
Kochi
Chennai
Ahmedabad
Kochi
Kochi
Kolkata
Hyderabad
Coimbatore
Pune
Chennai
Kolkata
Jaipur
Coimbatore
Hyderabad
Coimbatore
Jaipur
Chennai
Hyderabad
Ahmedabad
Chennai
Coimbatore
Kolkata
Ahmedabad
Bangalore
Coimbatore
Bangalore
Bangalore
Kolkata
Pune
Coimbatore
Hyderabad
Mumbai
Ahmedabad
Bangalore
Delhi
Mumbai
Delhi
Coimbatore
Hyderabad
Coimbatore
Jaipur
Hyderabad
Mumbai
Bangalore
Coimbatore
Mumbai
Bangalore
Hyderabad
Hyderabad
Kochi
Mumbai
Chennai
Pune
Hyderabad
Coimbatore
Kolkata
Mumbai
Hyderabad
Kolkata
Chennai
Kochi
Pune
Pune
Kochi
Bangalore
Mumbai
Coimbatore
Mumbai
Pune
Mumbai
Kolkata
Kolkata
Jaipur
Mumbai
Ahmedabad
Hyderabad
Kochi
Mumbai
Jaipur
Chennai
Kolkata
Bangalore
Mumbai
Pune
Coimbatore
Kochi
Chennai
Delhi
Coimbatore
Mumbai
Mumbai
Hyderabad
Jaipur
Pune
Mumbai
Hyderabad
Mumbai
Coimbatore
Pune
Delhi
Kolkata
Delhi
Kolkata
Jaipur
Coimbatore
Coimbatore
Chennai
Coimbatore
Kolkata
Hyderabad
Chennai
Jaipur
Coimbatore
Mumbai
Coimbatore
Mumbai
Coimbatore
Jaipur
Coimbatore
Bangalore
Delhi
Coimbatore
Ahmedabad
Kochi
Jaipur
Kochi
Jaipur
Hyderabad
Pune
Delhi
Jaipur
Kochi
Kolkata
Chennai
Kolkata
Mumbai
Mumbai
Ahmedabad
Bangalore
Delhi
Delhi
Hyderabad
Hyderabad
Kochi
Mumbai
Bangalore
Delhi
Pune
Coimbatore
Kochi
Hyderabad
Coimbatore
Jaipur
Mumbai
Pune
Hyderabad
Bangalore
Coimbatore
Jaipur
Kochi
Coimbatore
Coimbatore
Chennai
Pune
Hyderabad
Mumbai
Hyderabad
Mumbai
Delhi
Chennai
Bangalore
Delhi
Delhi
Pune
Hyderabad
Kolkata
Pune
Chennai
Bangalore
Ahmedabad
Kochi
Hyderabad
Kolkata
Jaipur
Hyderabad
Kolkata
Coimbatore
Kolkata
Mumbai
Kochi
Kolkata
Ahmedabad
Jaipur
Coimbatore
Bangalore
Pune
Hyderabad
Hyderabad
Jaipur
Kochi
Coimbatore
Pune
Mumbai
Delhi
Delhi
Pune
Kochi
Coimbatore
Kolkata
Kolkata
Mumbai
Mumbai
Kolkata
Mumbai
Coimbatore
Jaipur
Kolkata
Ahmedabad
Hyderabad
Jaipur
Coimbatore
Delhi
Chennai
Kochi
Pune
Bangalore
Kolkata
Pune
Kochi
Pune
Bangalore
Ahmedabad
Mumbai
Chennai
Bangalore
Mumbai
Bangalore
Pune
Kolkata
Delhi
Mumbai
Kochi
Chennai
Pune
Pune
Coimbatore
Pune
Chennai
Hyderabad
Hyderabad
Coimbatore
Chennai
Kolkata
Delhi
Jaipur
Hyderabad
Kochi
Hyderabad
Coimbatore
Mumbai
Chennai
Bangalore
Kolkata
Ahmedabad
Chennai
Coimbatore
Kochi
Pune
Kolkata
Chennai
Pune
Bangalore
Coimbatore
Kochi
Kochi
Delhi
Delhi
Pune
Kochi
Pune
Kochi
Coimbatore
Hyderabad
Hyderabad
Pune
Delhi
Bangalore
Mumbai
Delhi
Coimbatore
Chennai
Kochi
Hyderabad
Coimbatore
Hyderabad
Kolkata
Kolkata
Hyderabad
Coimbatore
Kolkata
Mumbai
Hyderabad
Hyderabad
Delhi
Coimbatore
Pune
Delhi
Hyderabad
Chennai
Delhi
Delhi
Hyderabad
Kolkata
Bangalore
Jaipur
Kolkata
Pune
Kolkata
Kochi
Hyderabad
Pune
Ahmedabad
Kochi
Hyderabad
Hyderabad
Kochi
Kolkata
Pune
Mumbai
Bangalore
Mumbai
Kolkata
Ahmedabad
Kochi
Kochi
Kolkata
Kolkata
Mumbai
Delhi
Mumbai
Pune
Bangalore
Kolkata
Hyderabad
Chennai
Kochi
Kolkata
Chennai
Delhi
Chennai
Pune
Delhi
Coimbatore
Coimbatore
Bangalore
Kolkata
Mumbai
Mumbai
Coimbatore
Pune
Jaipur
Kochi
Hyderabad
Chennai
Coimbatore
Ahmedabad
Hyderabad
Pune
Hyderabad
Pune
Kochi
Pune
Bangalore
Kolkata
Coimbatore
Coimbatore
Jaipur
Ahmedabad
Kochi
Jaipur
Delhi
Mumbai
Bangalore
Ahmedabad
Pune
Jaipur
Bangalore
Delhi
Hyderabad
Coimbatore
Chennai
Bangalore
Kochi
Coimbatore
Mumbai
Coimbatore
Pune
Kochi
Mumbai
Bangalore
Chennai
Kolkata
Mumbai
Delhi
Bangalore
Hyderabad
Chennai
Kochi
Delhi
Ahmedabad
Jaipur
Pune
Chennai
Ahmedabad
Kolkata
Ahmedabad
Hyderabad
Mumbai
Mumbai
Mumbai
Hyderabad
Delhi
Delhi
Kolkata
Pune
Jaipur
Kochi
Jaipur
Ahmedabad
Ahmedabad
Chennai
Hyderabad
Kochi
Kolkata
Jaipur
Mumbai
Ahmedabad
Chennai
Kolkata
Coimbatore
Hyderabad
Kolkata
Mumbai
Chennai
Pune
Hyderabad
Hyderabad
Mumbai
Mumbai
Mumbai
Kolkata
Coimbatore
Hyderabad
Mumbai
Mumbai
Chennai
Kolkata
Mumbai
Mumbai
Hyderabad
Jaipur
Mumbai
Mumbai
Bangalore
Delhi
Mumbai
Pune
Kolkata
Ahmedabad
Chennai
Coimbatore
Kolkata
Jaipur
Jaipur
Delhi
Pune
Chennai
Pune
Ahmedabad
Bangalore
Mumbai
Kochi
Pune
Mumbai
Kolkata
Hyderabad
Mumbai
Mumbai
Pune
Coimbatore
Delhi
Chennai
Ahmedabad
Pune
Coimbatore
Kochi
Chennai
Chennai
Kochi
Delhi
Kochi
Jaipur
Ahmedabad
Hyderabad
Bangalore
Kolkata
Delhi
Bangalore
Bangalore
Kochi
Mumbai
Mumbai
Kochi
Kolkata
Hyderabad
Chennai
Kochi
Mumbai
Kochi
Jaipur
Ahmedabad
Ahmedabad
Hyderabad
Bangalore
Jaipur
Bangalore
Mumbai
Pune
Kolkata
Kochi
Pune
Kolkata
Kolkata
Pune
Hyderabad
Hyderabad
Kochi
Jaipur
Hyderabad
Delhi
Delhi
Mumbai
Delhi
Kochi
Ahmedabad
Kolkata
Jaipur
Delhi
Hyderabad
Mumbai
Kochi
Coimbatore
Delhi
Mumbai
Delhi
Ahmedabad
Bangalore
Mumbai
Hyderabad
Delhi
Delhi
Chennai
Mumbai
Bangalore
Delhi
Jaipur
Ahmedabad
Pune
Kochi
Chennai
Coimbatore
Mumbai
Coimbatore
Coimbatore
Jaipur
Hyderabad
Coimbatore
Kochi
Coimbatore
Delhi
Pune
Chennai
Mumbai
Mumbai
Mumbai
Kochi
Mumbai
Coimbatore
Pune
Jaipur
Pune
Pune
Mumbai
Pune
Coimbatore
Bangalore
Delhi
Hyderabad
Chennai
Kochi
Bangalore
Ahmedabad
Kochi
Chennai
Mumbai
Mumbai
Coimbatore
Kolkata
Pune
Mumbai
Kolkata
Coimbatore
Kolkata
Jaipur
Pune
Kochi
Kochi
Hyderabad
Kolkata
Jaipur
Bangalore
Jaipur
Chennai
Bangalore
Delhi
Coimbatore
Kochi
Jaipur
Kochi
Bangalore
Pune
Jaipur
Mumbai
Pune
Kochi
Hyderabad
Pune
Mumbai
Hyderabad
Delhi
Coimbatore
Bangalore
Bangalore
Pune
Jaipur
Kochi
Kochi
Delhi
Coimbatore
Coimbatore
Mumbai
Jaipur
Kolkata
Kolkata
Kolkata
Kolkata
Mumbai
Kolkata
Mumbai
Ahmedabad
Mumbai
Mumbai
Pune
Delhi
Kolkata
Mumbai
Kolkata
Chennai
Pune
Delhi
Mumbai
Pune
Mumbai
Bangalore
Mumbai
Kochi
Kochi
Chennai
Kochi
Kochi
Coimbatore
Jaipur
Kolkata
Mumbai
Chennai
Pune
Mumbai
Hyderabad
Mumbai
Mumbai
Delhi
Hyderabad
Kochi
Chennai
Hyderabad
Chennai
Jaipur
Chennai
Chennai
Hyderabad
Kochi
Kochi
Kochi
Mumbai
Pune
Kolkata
Pune
Delhi
Coimbatore
Ahmedabad
Chennai
Mumbai
Hyderabad
Hyderabad
Kochi
Chennai
Pune
Chennai
Jaipur
Kolkata
Delhi
Hyderabad
Coimbatore
Mumbai
Hyderabad
Chennai
Delhi
Kochi
Kolkata
Kolkata
Mumbai
Hyderabad
Coimbatore
Kolkata
Bangalore
Kolkata
Mumbai
Pune
Chennai
Mumbai
Delhi
Delhi
Jaipur
Kolkata
Kochi
Kochi
Pune
Mumbai
Delhi
Delhi
Mumbai
Hyderabad
Kochi
Kochi
Mumbai
Hyderabad
Coimbatore
Mumbai
Delhi
Pune
Delhi
Bangalore
Mumbai
Kochi
Hyderabad
Kochi
Kolkata
Hyderabad
Pune
Chennai
Coimbatore
Bangalore
Mumbai
Chennai
Hyderabad
Chennai
Hyderabad
Coimbatore
Delhi
Kolkata
Coimbatore
Pune
Coimbatore
Hyderabad
Jaipur
Chennai
Chennai
Pune
Delhi
Bangalore
Jaipur
Mumbai
Coimbatore
Mumbai
Hyderabad
Pune
Coimbatore
Kochi
Kolkata
Kolkata
Coimbatore
Coimbatore
Hyderabad
Pune
Delhi
Delhi
Coimbatore
Mumbai
Chennai
Pune
Bangalore
Coimbatore
Kolkata
Chennai
Mumbai
Kochi
Mumbai
Pune
Kochi
Pune
Kolkata
Mumbai
Jaipur
Pune
Kolkata
Mumbai
Chennai
Bangalore
Mumbai
Mumbai
Chennai
Kochi
Chennai
Kochi
Coimbatore
Delhi
Kolkata
Jaipur
Mumbai
Mumbai
Pune
Hyderabad
Kochi
Coimbatore
Delhi
Pune
Jaipur
Kolkata
Kochi
Bangalore
Hyderabad
Jaipur
Pune
Kolkata
Kochi
Chennai
Jaipur
Mumbai
Mumbai
Delhi
Mumbai
Kochi
Hyderabad
Kochi
Coimbatore
Bangalore
Chennai
Delhi
Bangalore
Kolkata
Delhi
Pune
Jaipur
Mumbai
Kochi
Ahmedabad
Jaipur
Pune
Mumbai
Kochi
Hyderabad
Kochi
Kochi
Kolkata
Pune
Coimbatore
Kochi
Delhi
Coimbatore
Jaipur
Bangalore
Jaipur
Mumbai
Hyderabad
Coimbatore
Mumbai
Coimbatore
Pune
Pune
Coimbatore
Hyderabad
Kolkata
Mumbai
Delhi
Pune
Delhi
Coimbatore
Hyderabad
Hyderabad
Kolkata
Delhi
Delhi
Jaipur
Kochi
Kochi
Pune
Mumbai
Pune
Hyderabad
Coimbatore
Jaipur
Mumbai
Coimbatore
Bangalore
Kochi
Delhi
Coimbatore
Delhi
Coimbatore
Kolkata
Delhi
Coimbatore
Pune
Chennai
Pune
Kochi
Coimbatore
Kochi
Coimbatore
Mumbai
Kochi
Mumbai
Chennai
Hyderabad
Mumbai
Mumbai
Jaipur
Pune
Chennai
Pune
Pune
Delhi
Pune
Kochi
Hyderabad
Mumbai
Coimbatore
Kochi
Delhi
Kolkata
Mumbai
Pune
Ahmedabad
Hyderabad
Chennai
Hyderabad
Hyderabad
Kochi
Coimbatore
Pune
Kolkata
Mumbai
Delhi
Mumbai
Kolkata
Pune
Delhi
Chennai
Kolkata
Kolkata
Jaipur
Coimbatore
Kolkata
Hyderabad
Jaipur
Kochi
Hyderabad
Hyderabad
Kochi
Hyderabad
Hyderabad
Ahmedabad
Pune
Jaipur
Jaipur
Coimbatore
Kochi
Kochi
Kochi
Chennai
Delhi
Chennai
Delhi
Mumbai
Pune
Hyderabad
Chennai
Coimbatore
Mumbai
Jaipur
Coimbatore
Mumbai
Pune
Jaipur
Pune
Kochi
Kolkata
Pune
Chennai
Mumbai
Hyderabad
Kochi
Chennai
Kolkata
Pune
Mumbai
Coimbatore
Kochi
Mumbai
Mumbai
Pune
Coimbatore
Coimbatore
Hyderabad
Chennai
Delhi
Kochi
Kochi
Pune
Kolkata
Delhi
Kolkata
Pune
Kochi
Pune
Coimbatore
Mumbai
Bangalore
Pune
Kochi
Bangalore
Mumbai
Coimbatore
Hyderabad
Kolkata
Bangalore
Kochi
Hyderabad
Pune
Kochi
Kochi
Mumbai
Jaipur
Hyderabad
Kochi
Kolkata
Kolkata
Hyderabad
Kolkata
Kolkata
Kolkata
Ahmedabad
Mumbai
Coimbatore
Kochi
Kolkata
Mumbai
Pune
Coimbatore
Bangalore
Jaipur
Mumbai
Hyderabad
Delhi
Chennai
Pune
Hyderabad
Delhi
Delhi
Mumbai
Kochi
Pune
Hyderabad
Pune
Pune
Coimbatore
Coimbatore
Mumbai
Chennai
Delhi
Mumbai
Jaipur
Coimbatore
Ahmedabad
Kolkata
Hyderabad
Pune
Ahmedabad
Chennai
Delhi
Delhi
Jaipur
Bangalore
Delhi
Kochi
Kochi
Delhi
Hyderabad
Delhi
Mumbai
Mumbai
Delhi
Delhi
Pune
Kolkata
Kochi
Pune
Jaipur
Pune
Kolkata
Chennai
Chennai
Kochi
Delhi
Delhi
Mumbai
Coimbatore
Mumbai
Kolkata
Delhi
Kochi
Kochi
Kolkata
Jaipur
Coimbatore
Kolkata
Kolkata
Delhi
Coimbatore
Delhi
Ahmedabad
Kolkata
Hyderabad
Kochi
Hyderabad
Bangalore
Delhi
Kochi
Delhi
Ahmedabad
Mumbai
Kochi
Chennai
Coimbatore
Mumbai
Jaipur
Kochi
Mumbai
Delhi
Pune
Kochi
Kochi
Coimbatore
Coimbatore
Coimbatore
Mumbai
Ahmedabad
Chennai
Mumbai
Kolkata
Mumbai
Kolkata
Jaipur
Ahmedabad
Coimbatore
Chennai
Delhi
Kolkata
Hyderabad
Mumbai
Hyderabad
Mumbai
Mumbai
Kochi
Coimbatore
Coimbatore
Mumbai
Bangalore
Delhi
Jaipur
Bangalore
Pune
Delhi
Delhi
Hyderabad
Kochi
Bangalore
Chennai
Mumbai
Hyderabad
Ahmedabad
Pune
Hyderabad
Chennai
Delhi
Kochi
Kochi
Kolkata
Kochi
Pune
Chennai
Hyderabad
Coimbatore
Pune
Jaipur
Kochi
Mumbai
Hyderabad
Kolkata
Hyderabad
Mumbai
Chennai
Bangalore
Chennai
Chennai
Pune
Mumbai
Hyderabad
Mumbai
Kochi
Hyderabad
Bangalore
Coimbatore
Chennai
Delhi
Hyderabad
Mumbai
Pune
Pune
Pune
Pune
Bangalore
Mumbai
Ahmedabad
Bangalore
Kochi
Hyderabad
Pune
Mumbai
Kolkata
Jaipur
Kochi
Chennai
Coimbatore
Delhi
Mumbai
Pune
Bangalore
Pune
Bangalore
Kolkata
Bangalore
Delhi
Coimbatore
Mumbai
Jaipur
Chennai
Coimbatore
Mumbai
Pune
Kolkata
Pune
Hyderabad
Hyderabad
Mumbai
Hyderabad
Kolkata
Hyderabad
Bangalore
Hyderabad
Coimbatore
Ahmedabad
Delhi
Hyderabad
Mumbai
Coimbatore
Hyderabad
Jaipur
Mumbai
Chennai
Ahmedabad
Hyderabad
Mumbai
Kochi
Kochi
Kolkata
Kochi
Mumbai
Bangalore
Coimbatore
Kolkata
Pune
Chennai
Delhi
Delhi
Pune
Chennai
Jaipur
Pune
Pune
Mumbai
Hyderabad
Pune
Chennai
Kolkata
Jaipur
Jaipur
Kolkata
Mumbai
Mumbai
Hyderabad
Bangalore
Mumbai
Hyderabad
Coimbatore
Hyderabad
Delhi
Mumbai
Mumbai
Jaipur
Hyderabad
Chennai
Kolkata
Coimbatore
Coimbatore
Hyderabad
Ahmedabad
Mumbai
Mumbai
Kolkata
Mumbai
Mumbai
Coimbatore
Jaipur
Pune
Hyderabad
Coimbatore
Hyderabad
Pune
Kochi
Jaipur
Pune
Hyderabad
Kolkata
Hyderabad
Kochi
Delhi
Mumbai
Coimbatore
Coimbatore
Delhi
Mumbai
Kochi
Bangalore
Pune
Mumbai
Hyderabad
Delhi
Coimbatore
Mumbai
Jaipur
Pune
Pune
Bangalore
Kolkata
Hyderabad
Delhi
Kochi
Chennai
Chennai
Pune
Coimbatore
Mumbai
Hyderabad
Bangalore
Mumbai
Coimbatore
Delhi
Coimbatore
Hyderabad
Kolkata
Mumbai
Kolkata
Kolkata
Jaipur
Delhi
Ahmedabad
Kochi
Mumbai
Kochi
Pune
Mumbai
Hyderabad
Coimbatore
Kochi
Mumbai
Bangalore
Pune
Mumbai
Kochi
Coimbatore
Chennai
Hyderabad
Jaipur
Mumbai
Hyderabad
Mumbai
Delhi
Mumbai
Mumbai
Bangalore
Kolkata
Hyderabad
Ahmedabad
Chennai
Mumbai
Coimbatore
Mumbai
Kochi
Jaipur
Mumbai
Coimbatore
Mumbai
Kolkata
Coimbatore
Delhi
Ahmedabad
Delhi
Mumbai
Bangalore
Jaipur
Hyderabad
Pune
Mumbai
Kolkata
Mumbai
Hyderabad
Pune
Chennai
Delhi
Delhi
Mumbai
Kolkata
Ahmedabad
Delhi
Kochi
Hyderabad
Pune
Mumbai
Jaipur
Delhi
Pune
Kochi
Ahmedabad
Chennai
Kochi
Mumbai
Coimbatore
Kolkata
Kochi
Pune
Hyderabad
Delhi
Kolkata
Delhi
Bangalore
Hyderabad
Jaipur
Hyderabad
Coimbatore
Hyderabad
Mumbai
Kochi
Mumbai
Bangalore
Kolkata
Kolkata
Bangalore
Hyderabad
Hyderabad
Hyderabad
Chennai
Coimbatore
Ahmedabad
Delhi
Hyderabad
Mumbai
Bangalore
Ahmedabad
Hyderabad
Bangalore
Coimbatore
Pune
Kolkata
Jaipur
Pune
Mumbai
Mumbai
Mumbai
Mumbai
Pune
Pune
Pune
Delhi
Jaipur
Mumbai
Pune
Kochi
Kolkata
Jaipur
Bangalore
Jaipur
Pune
Delhi
Kochi
Hyderabad
Bangalore
Kolkata
Kochi
Chennai
Kochi
Coimbatore
Delhi
Coimbatore
Delhi
Mumbai
Hyderabad
Hyderabad
Bangalore
Jaipur
Coimbatore
Chennai
Delhi
Mumbai
Hyderabad
Chennai
Mumbai
Delhi
Delhi
Coimbatore
Kolkata
Mumbai
Mumbai
Kolkata
Kolkata
Delhi
Bangalore
Coimbatore
Kolkata
Mumbai
Pune
Delhi
Chennai
Pune
Coimbatore
Coimbatore
Chennai
Jaipur
Mumbai
Chennai
Hyderabad
Mumbai
Ahmedabad
Mumbai
Jaipur
Kochi
Bangalore
Pune
Jaipur
Mumbai
Coimbatore
Hyderabad
Kochi
Hyderabad
Chennai
Bangalore
Delhi
Hyderabad
Bangalore
Kolkata
Bangalore
Coimbatore
Delhi
Delhi
Coimbatore
Delhi
Kolkata
Chennai
Delhi
Ahmedabad
Delhi
Coimbatore
Chennai
Delhi
Kolkata
Kochi
Chennai
Chennai
Mumbai
Pune
Jaipur
Delhi
Kochi
Jaipur
Hyderabad
Hyderabad
Coimbatore
Jaipur
Mumbai
Delhi
Coimbatore
Pune
Delhi
Hyderabad
Kolkata
Delhi
Ahmedabad
Coimbatore
Kochi
Kochi
Kolkata
Chennai
Chennai
Hyderabad
Pune
Kolkata
Coimbatore
Ahmedabad
Hyderabad
Kochi
Delhi
Kochi
Hyderabad
Coimbatore
Jaipur
Chennai
Pune
Hyderabad
Jaipur
Delhi
Kolkata
Kochi
Kolkata
Kochi
Pune
Ahmedabad
Coimbatore
Delhi
Pune
Pune
Delhi
Mumbai
Jaipur
Chennai
Pune
Kolkata
Chennai
Coimbatore
Kolkata
Mumbai
Chennai
Kolkata
Kolkata
Kochi
Jaipur
Chennai
Hyderabad
Kolkata
Delhi
Kolkata
Jaipur
Delhi
Coimbatore
Ahmedabad
Mumbai
Coimbatore
Coimbatore
Coimbatore
Kolkata
Jaipur
Mumbai
Chennai
Mumbai
Delhi
Pune
Delhi
Hyderabad
Mumbai
Kolkata
Mumbai
Mumbai
Delhi
Delhi
Bangalore
Pune
Chennai
Pune
Jaipur
Kochi
Chennai
Coimbatore
Coimbatore
Coimbatore
Delhi
Delhi
Kochi
Chennai
Kochi
Delhi
Hyderabad
Bangalore
Delhi
Chennai
Kochi
Kochi
Chennai
Coimbatore
Pune
Mumbai
Mumbai
Kochi
Bangalore
Jaipur
Mumbai
Mumbai
Hyderabad
Pune
Coimbatore
Hyderabad
Hyderabad
Jaipur
Kolkata
Kochi
Hyderabad
Coimbatore
Hyderabad
Chennai
Mumbai
Mumbai
Ahmedabad
Coimbatore
Kochi
Kolkata
Delhi
Mumbai
Bangalore
Ahmedabad
Pune
Kochi
Coimbatore
Bangalore
Ahmedabad
Chennai
Hyderabad
Mumbai
Pune
Delhi
Hyderabad
Kochi
Mumbai
Hyderabad
Coimbatore
Kolkata
Hyderabad
Coimbatore
Coimbatore
Jaipur
Pune
Jaipur
Kochi
Bangalore
Hyderabad
Pune
Coimbatore
Hyderabad
Chennai
Kolkata
Pune
Delhi
Coimbatore
Hyderabad
Coimbatore
Hyderabad
Pune
Mumbai

In [44]:
list1 = []
for i in df_cars['Location']:
  if ((i == 'Mumbai') | (i == 'Chennai')):
    list1.append(i)
print(len(list1))

1285

In [45]:
df_cars.value_counts('Location')

Location
Mumbai        790
Hyderabad     742
Kochi         651
Coimbatore    636
Pune          622
Delhi         554
Kolkata       535
Chennai       495
Jaipur        413
Bangalore     358
Ahmedabad     224
Name: count, dtype: int64

## Filtering

In [46]:
df_cars[df_cars['Location'] == 'Mumbai']

,id,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Updated_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
8,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,Diesel,Automatic,First,11.36 kmpl,2755 CC,171.5 bhp,8.0,21 Lakh,17.50
23,22,Audi A6 2011-2015 35 TFSI Technology,Mumbai,2015,55985,Petrol,Automatic,First,13.53 kmpl,1984 CC,177.01 bhp,5.0,NaN,23.50
26,25,Honda City Corporate Edition,Mumbai,2012,51920,Petrol,Manual,First,16.8 kmpl,1497 CC,116.3 bhp,5.0,NaN,4.25
30,29,Toyota Innova 2.5 V Diesel 7-seater,Mumbai,2007,262000,Diesel,Manual,Fourth & Above,12.8 kmpl,2494 CC,102 bhp,7.0,NaN,4.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5993,5992,Skoda Superb Elegance 1.8 TSI AT,Mumbai,2011,42036,Petrol,Automatic,First,13.7 kmpl,1798 CC,157.75 bhp,5.0,NaN,6.25
5994,5993,Hyundai Elantra SX,Mumbai,2014,55619,Petrol,Manual,First,16.3 kmpl,1797 CC,147.5 bhp,5.0,NaN,8.30
6003,6002,Volkswagen Vento 1.6 Highline,Mumbai,2011,38000,Petrol,Manual,First,16.09 kmpl,1598 CC,103.5 bhp,5.0,11.91 Lakh,3.25
6007,6006,Mercedes-Benz M-Class ML 320 CDI,Mumbai,2009,102002,Diesel,Automatic,First,8.7 kmpl,2987 CC,224.34 bhp,5.0,NaN,10.75
6010,6009,Toyota Camry Hybrid,Mumbai,2015,33500,Petrol,Automatic,First,19.16 kmpl,2494 CC,158.2 bhp,5.0,NaN,19.75

In [47]:
df_cars[df_cars['Location'] == 'Mumbai'].to_excel('Selected_cars.xlsx', index=False)

In [48]:
d f_cars

,id,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Updated_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
4,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6015,6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,7.88 Lakh,4.75
6016,6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.0,NaN,4.00
6017,6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.0,NaN,2.90
6018,6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.0,NaN,2.65
6019,6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,NaN,2.50